# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childcare_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='check',
            name='on_site',
            field=models.NullBooleanField(default=False),
        ),
    ]
