# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childcare_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='child',
        ),
        migrations.AddField(
            model_name='child',
            name='code',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pin',
        ),
    ]
