# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childcare_app', '0002_auto_20161103_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
