# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childcare_app', '0004_auto_20161104_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
    ]
